import type { MissionDefinition } from "@/types"

export const PHASES = [
  { name: "Python Foundations", description: "Core Python syntax and programming concepts", missions: [1, 2, 3, 4, 5, 6, 7, 8] },
  { name: "Data Structures", description: "Working with collections and iterators", missions: [9, 10, 11, 12, 13, 14] },
  { name: "Files & APIs", description: "Reading data from files and web services", missions: [15, 16, 17, 18] },
  { name: "Data Engineering", description: "Professional data tools and libraries", missions: [19, 20, 21, 22, 23] },
  { name: "ETL Pipelines", description: "Extract, transform, load workflows", missions: [24, 25, 26, 27] },
  { name: "Production", description: "APIs, containers, testing, deployment", missions: [28, 29, 30, 31] },
]

export const MISSIONS: MissionDefinition[] = [
  // ===== PHASE 1: Python Foundations =====
  {
    id: 1,
    title: "Hello, Python!",
    phase: "Python Foundations",
    difficulty: 1,
    estimatedMinutes: 20,
    xp: 50,
    goal: "Write your first Python program and understand what a variable is.",
    learningObjectives: [
      "Use the print() function",
      "Create and assign variables",
      "Understand basic data types (str, int, float)",
      "Write comments",
    ],
    prerequisites: [],
    projectFeature: "Display welcome message for the Crypto Exchange Analyzer.",
    officialSources: ["https://docs.python.org/3/tutorial/introduction.html"],
    requiredQuizScore: 75,
    orderIndex: 1,
  },
  {
    id: 2,
    title: "Data Types & Operators",
    phase: "Python Foundations",
    difficulty: 1,
    estimatedMinutes: 25,
    xp: 60,
    goal: "Work with different data types and perform calculations.",
    learningObjectives: [
      "Use int, float, str, bool types",
      "Perform arithmetic operations",
      "Use comparison operators",
      "Type conversion with int(), float(), str()",
    ],
    prerequisites: [1],
    projectFeature: "Calculate basic crypto trading metrics (price difference, percentage change).",
    officialSources: ["https://docs.python.org/3/library/stdtypes.html"],
    requiredQuizScore: 75,
    orderIndex: 2,
  },
  {
    id: 3,
    title: "Input & Output",
    phase: "Python Foundations",
    difficulty: 1,
    estimatedMinutes: 25,
    xp: 60,
    goal: "Make interactive programs that respond to user input.",
    learningObjectives: [
      "Use input() to get user data",
      "Format strings with f-strings",
      "Handle input type conversion",
      "Basic error prevention",
    ],
    prerequisites: [1, 2],
    projectFeature: "Ask user for crypto symbol and display formatted price info.",
    officialSources: ["https://docs.python.org/3/tutorial/inputoutput.html"],
    requiredQuizScore: 75,
    orderIndex: 3,
  },
  {
    id: 4,
    title: "Decision Engine",
    phase: "Python Foundations",
    difficulty: 1,
    estimatedMinutes: 30,
    xp: 80,
    goal: "Make programs that make decisions using conditions.",
    learningObjectives: [
      "Use if, elif, else statements",
      "Combine conditions with and, or, not",
      "Nested conditions",
      "Truthy and falsy values",
    ],
    prerequisites: [1, 2, 3],
    projectFeature: "Build a trading signal engine: BUY, SELL, or HOLD based on price thresholds.",
    officialSources: ["https://docs.python.org/3/tutorial/controlflow.html#if-statements"],
    requiredQuizScore: 80,
    orderIndex: 4,
  },
  {
    id: 5,
    title: "Loops",
    phase: "Python Foundations",
    difficulty: 2,
    estimatedMinutes: 30,
    xp: 90,
    goal: "Automate repetitive tasks with loops.",
    learningObjectives: [
      "Use for loops with range()",
      "Iterate over strings and lists",
      "Use while loops",
      "break and continue statements",
    ],
    prerequisites: [4],
    projectFeature: "Process multiple crypto prices in a loop and calculate averages.",
    officialSources: ["https://docs.python.org/3/tutorial/controlflow.html#for-statements"],
    requiredQuizScore: 80,
    orderIndex: 5,
  },
  {
    id: 6,
    title: "Lists",
    phase: "Python Foundations",
    difficulty: 2,
    estimatedMinutes: 30,
    xp: 90,
    goal: "Store and manipulate ordered collections of data.",
    learningObjectives: [
      "Create and access lists",
      "List methods: append, remove, pop, sort",
      "List slicing [start:stop:step]",
      "Nested lists",
    ],
    prerequisites: [5],
    projectFeature: "Store historical prices in a list and compute simple moving averages.",
    officialSources: ["https://docs.python.org/3/tutorial/datastructures.html#more-on-lists"],
    requiredQuizScore: 80,
    orderIndex: 6,
  },
  {
    id: 7,
    title: "Functions",
    phase: "Python Foundations",
    difficulty: 2,
    estimatedMinutes: 35,
    xp: 100,
    goal: "Write reusable, organized code with functions.",
    learningObjectives: [
      "Define functions with def",
      "Parameters and arguments",
      "Return values",
      "Scope (local vs global variables)",
    ],
    prerequisites: [6],
    projectFeature: "Move price calculations into reusable functions.",
    officialSources: ["https://docs.python.org/3/tutorial/controlflow.html#defining-functions"],
    requiredQuizScore: 80,
    orderIndex: 7,
  },
  {
    id: 8,
    title: "Error Handling",
    phase: "Python Foundations",
    difficulty: 2,
    estimatedMinutes: 30,
    xp: 80,
    goal: "Write robust code that handles errors gracefully.",
    learningObjectives: [
      "Use try/except blocks",
      "Handle specific exceptions",
      "Use else and finally",
      "Raise exceptions intentionally",
    ],
    prerequisites: [7],
    projectFeature: "Add input validation and error handling to the crypto analyzer.",
    officialSources: ["https://docs.python.org/3/tutorial/errors.html"],
    requiredQuizScore: 80,
    orderIndex: 8,
  },

  // ===== PHASE 2: Data Structures =====
  {
    id: 9,
    title: "Tuples & Sets",
    phase: "Data Structures",
    difficulty: 2,
    estimatedMinutes: 30,
    xp: 80,
    goal: "Use immutable sequences and unique collections.",
    learningObjectives: [
      "Create and use tuples",
      "Tuple unpacking",
      "Create and use sets",
      "Set operations (union, intersection, difference)",
    ],
    prerequisites: [8],
    projectFeature: "Store trading pairs as tuples and track unique exchanges with sets.",
    officialSources: ["https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences"],
    requiredQuizScore: 80,
    orderIndex: 9,
  },
  {
    id: 10,
    title: "Dictionaries",
    phase: "Data Structures",
    difficulty: 2,
    estimatedMinutes: 35,
    xp: 100,
    goal: "Master key-value data storage.",
    learningObjectives: [
      "Create and access dictionaries",
      "Dictionary methods: get, keys, values, items",
      "Nested dictionaries",
      "Dictionary comprehensions (intro)",
    ],
    prerequisites: [9],
    projectFeature: "Build a crypto portfolio tracker using dictionaries.",
    officialSources: ["https://docs.python.org/3/tutorial/datastructures.html#dictionaries"],
    requiredQuizScore: 80,
    orderIndex: 10,
  },
  {
    id: 11,
    title: "Comprehensions",
    phase: "Data Structures",
    difficulty: 2,
    estimatedMinutes: 30,
    xp: 90,
    goal: "Write concise, Pythonic data transformations.",
    learningObjectives: [
      "List comprehensions",
      "Dict comprehensions",
      "Set comprehensions",
      "Filtering with if in comprehensions",
    ],
    prerequisites: [10],
    projectFeature: "Transform exchange data efficiently with comprehensions.",
    officialSources: ["https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions"],
    requiredQuizScore: 80,
    orderIndex: 11,
  },
  {
    id: 12,
    title: "Iterators & Generators",
    phase: "Data Structures",
    difficulty: 3,
    estimatedMinutes: 35,
    xp: 110,
    goal: "Understand lazy evaluation and memory-efficient iteration.",
    learningObjectives: [
      "iter() and next()",
      "Create generators with yield",
      "Generator expressions",
      "Memory efficiency concepts",
    ],
    prerequisites: [11],
    projectFeature: "Stream large price datasets with generators.",
    officialSources: ["https://docs.python.org/3/tutorial/classes.html#iterators"],
    requiredQuizScore: 80,
    orderIndex: 12,
  },
  {
    id: 13,
    title: "String Manipulation",
    phase: "Data Structures",
    difficulty: 2,
    estimatedMinutes: 25,
    xp: 70,
    goal: "Master text processing techniques.",
    learningObjectives: [
      "String methods: split, join, strip, replace",
      "Regular expressions with re module",
      "String formatting techniques",
      "Unicode handling basics",
    ],
    prerequisites: [8],
    projectFeature: "Parse and clean exchange names and trading pair strings.",
    officialSources: ["https://docs.python.org/3/library/string.html", "https://docs.python.org/3/library/re.html"],
    requiredQuizScore: 80,
    orderIndex: 13,
  },
  {
    id: 14,
    title: "Collections Module",
    phase: "Data Structures",
    difficulty: 3,
    estimatedMinutes: 30,
    xp: 90,
    goal: "Use specialized container datatypes from the standard library.",
    learningObjectives: [
      "namedtuple for lightweight objects",
      "defaultdict for default values",
      "Counter for counting",
      "deque for efficient queues",
    ],
    prerequisites: [12],
    projectFeature: "Track trade frequency with Counter and order book with deque.",
    officialSources: ["https://docs.python.org/3/library/collections.html"],
    requiredQuizScore: 80,
    orderIndex: 14,
  },

  // ===== PHASE 3: Files & APIs =====
  {
    id: 15,
    title: "File I/O",
    phase: "Files & APIs",
    difficulty: 2,
    estimatedMinutes: 30,
    xp: 80,
    goal: "Read from and write to files on disk.",
    learningObjectives: [
      "Open files with open()",
      "Read modes: r, w, a",
      "Use with statements (context managers)",
      "Read lines and parse text files",
    ],
    prerequisites: [8],
    projectFeature: "Save and load exchange data from text files.",
    officialSources: ["https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files"],
    requiredQuizScore: 80,
    orderIndex: 15,
  },
  {
    id: 16,
    title: "CSV Processing",
    phase: "Files & APIs",
    difficulty: 2,
    estimatedMinutes: 30,
    xp: 90,
    goal: "Work with tabular data using the csv module.",
    learningObjectives: [
      "Read CSV with csv.reader()",
      "Write CSV with csv.writer()",
      "DictReader and DictWriter",
      "Handle headers and encoding",
    ],
    prerequisites: [15],
    projectFeature: "Import exchange rate history from CSV files.",
    officialSources: ["https://docs.python.org/3/library/csv.html"],
    requiredQuizScore: 80,
    orderIndex: 16,
  },
  {
    id: 17,
    title: "JSON & APIs",
    phase: "Files & APIs",
    difficulty: 3,
    estimatedMinutes: 35,
    xp: 110,
    goal: "Work with JSON data and make HTTP requests.",
    learningObjectives: [
      "Parse JSON with json.loads()",
      "Serialize with json.dumps()",
      "Make HTTP requests with requests library",
      "Handle API responses and status codes",
    ],
    prerequisites: [16],
    projectFeature: "Fetch live crypto prices from a public REST API.",
    officialSources: ["https://docs.python.org/3/library/json.html"],
    requiredQuizScore: 80,
    orderIndex: 17,
  },
  {
    id: 18,
    title: "API Authentication & Rate Limiting",
    phase: "Files & APIs",
    difficulty: 3,
    estimatedMinutes: 35,
    xp: 100,
    goal: "Work with authenticated APIs and handle rate limits.",
    learningObjectives: [
      "API key authentication",
      "Rate limit handling with time.sleep()",
      "Error handling for API failures",
      "Environment variables with os.getenv()",
    ],
    prerequisites: [17],
    projectFeature: "Connect to CoinGecko or Binance API with proper error handling.",
    officialSources: ["https://docs.python.org/3/library/os.html#os.getenv"],
    requiredQuizScore: 80,
    orderIndex: 18,
  },

  // ===== PHASE 4: Data Engineering =====
  {
    id: 19,
    title: "NumPy Essentials",
    phase: "Data Engineering",
    difficulty: 3,
    estimatedMinutes: 40,
    xp: 120,
    goal: "Perform fast numerical computations with NumPy.",
    learningObjectives: [
      "Create numpy arrays",
      "Array operations and broadcasting",
      "Statistical functions (mean, std, median)",
      "Boolean indexing",
    ],
    prerequisites: [12],
    projectFeature: "Compute advanced price statistics with NumPy arrays.",
    officialSources: ["https://numpy.org/doc/stable/user/quickstart.html"],
    requiredQuizScore: 80,
    orderIndex: 19,
  },
  {
    id: 20,
    title: "Pandas Fundamentals",
    phase: "Data Engineering",
    difficulty: 3,
    estimatedMinutes: 45,
    xp: 130,
    goal: "Master DataFrames for tabular data analysis.",
    learningObjectives: [
      "Create DataFrames from dicts, lists, CSV",
      "Select columns and rows (loc, iloc)",
      "Filter and sort data",
      "Basic aggregations (groupby)",
    ],
    prerequisites: [19],
    projectFeature: "Build a full crypto data analysis pipeline with Pandas.",
    officialSources: ["https://pandas.pydata.org/docs/getting_started/intro_tutorials/"],
    requiredQuizScore: 80,
    orderIndex: 20,
  },
  {
    id: 21,
    title: "Pandas Advanced",
    phase: "Data Engineering",
    difficulty: 3,
    estimatedMinutes: 40,
    xp: 120,
    goal: "Advanced data manipulation with Pandas.",
    learningObjectives: [
      "Merge and join DataFrames",
      "Pivot tables",
      "Time series handling",
      "Apply and transform",
    ],
    prerequisites: [20],
    projectFeature: "Merge multiple exchange data sources and create pivot reports.",
    officialSources: ["https://pandas.pydata.org/docs/user_guide/merging.html"],
    requiredQuizScore: 80,
    orderIndex: 21,
  },
  {
    id: 22,
    title: "DuckDB",
    phase: "Data Engineering",
    difficulty: 3,
    estimatedMinutes: 40,
    xp: 120,
    goal: "Query data with SQL using an embedded analytical database.",
    learningObjectives: [
      "Connect to DuckDB",
      "Run SQL queries on DataFrames",
      "Import/export CSV and Parquet",
      "Aggregations and window functions",
    ],
    prerequisites: [21],
    projectFeature: "Run complex SQL analytics on crypto data with DuckDB.",
    officialSources: ["https://duckdb.org/docs/"],
    requiredQuizScore: 80,
    orderIndex: 22,
  },
  {
    id: 23,
    title: "PyArrow & Parquet",
    phase: "Data Engineering",
    difficulty: 3,
    estimatedMinutes: 35,
    xp: 100,
    goal: "Work with columnar data formats for high performance.",
    learningObjectives: [
      "Read/write Parquet files",
      "Arrow tables vs Pandas",
      "Columnar data concepts",
      "Performance comparison",
    ],
    prerequisites: [22],
    projectFeature: "Store and query historical data in Parquet format.",
    officialSources: ["https://arrow.apache.org/docs/python/"],
    requiredQuizScore: 80,
    orderIndex: 23,
  },

  // ===== PHASE 5: ETL =====
  {
    id: 24,
    title: "Data Cleaning",
    phase: "ETL Pipelines",
    difficulty: 3,
    estimatedMinutes: 35,
    xp: 110,
    goal: "Clean and prepare messy real-world data.",
    learningObjectives: [
      "Handle missing values",
      "Remove duplicates",
      "Fix data types",
      "Outlier detection",
    ],
    prerequisites: [20],
    projectFeature: "Clean raw exchange data from multiple sources.",
    officialSources: ["https://pandas.pydata.org/docs/user_guide/missing_data.html"],
    requiredQuizScore: 80,
    orderIndex: 24,
  },
  {
    id: 25,
    title: "Data Validation",
    phase: "ETL Pipelines",
    difficulty: 3,
    estimatedMinutes: 30,
    xp: 90,
    goal: "Validate data quality programmatically.",
    learningObjectives: [
      "Schema validation concepts",
      "Write validation rules",
      "Data quality metrics",
      "Generate validation reports",
    ],
    prerequisites: [24],
    projectFeature: "Validate incoming exchange data before processing.",
    officialSources: ["https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.validate.html"],
    requiredQuizScore: 80,
    orderIndex: 25,
  },
  {
    id: 26,
    title: "Transformations",
    phase: "ETL Pipelines",
    difficulty: 4,
    estimatedMinutes: 40,
    xp: 120,
    goal: "Build reusable data transformation pipelines.",
    learningObjectives: [
      "Chain transformations",
      "Feature engineering basics",
      "Normalization and scaling",
      "Date/time transformations",
    ],
    prerequisites: [25],
    projectFeature: "Build feature engineering pipeline for trading signals.",
    officialSources: ["https://pandas.pydata.org/docs/user_guide/10min.html"],
    requiredQuizScore: 80,
    orderIndex: 26,
  },
  {
    id: 27,
    title: "ETL Pipeline Design",
    phase: "ETL Pipelines",
    difficulty: 4,
    estimatedMinutes: 45,
    xp: 140,
    goal: "Design and implement complete ETL workflows.",
    learningObjectives: [
      "Extract from multiple sources",
      "Transform with validation",
      "Load to database/files",
      "Pipeline orchestration basics",
    ],
    prerequisites: [26],
    projectFeature: "Build complete ETL pipeline: fetch → clean → store crypto data.",
    officialSources: ["https://docs.python.org/3/howto/logging.html"],
    requiredQuizScore: 80,
    orderIndex: 27,
  },

  // ===== PHASE 6: Production =====
  {
    id: 28,
    title: "FastAPI Basics",
    phase: "Production",
    difficulty: 3,
    estimatedMinutes: 40,
    xp: 120,
    goal: "Build REST APIs with FastAPI.",
    learningObjectives: [
      "Create FastAPI app",
      "Define routes and path parameters",
      "Request/response models with Pydantic",
      "Auto-generated docs",
    ],
    prerequisites: [18],
    projectFeature: "Create a REST API serving crypto analysis results.",
    officialSources: ["https://fastapi.tiangolo.com/tutorial/first-steps/"],
    requiredQuizScore: 80,
    orderIndex: 28,
  },
  {
    id: 29,
    title: "FastAPI Advanced",
    phase: "Production",
    difficulty: 4,
    estimatedMinutes: 45,
    xp: 130,
    goal: "Production-grade APIs with middleware and background tasks.",
    learningObjectives: [
      "Dependency injection",
      "Middleware",
      "Background tasks",
      "Error handling middleware",
    ],
    prerequisites: [28],
    projectFeature: "Add caching and rate limiting to the crypto API.",
    officialSources: ["https://fastapi.tiangolo.com/tutorial/middleware/"],
    requiredQuizScore: 80,
    orderIndex: 29,
  },
  {
    id: 30,
    title: "Docker",
    phase: "Production",
    difficulty: 3,
    estimatedMinutes: 35,
    xp: 100,
    goal: "Containerize Python applications.",
    learningObjectives: [
      "Write Dockerfiles",
      "Build and run containers",
      "Docker Compose for multi-service",
      "Volume mounting for dev",
    ],
    prerequisites: [29],
    projectFeature: "Dockerize the crypto analyzer API with Docker Compose.",
    officialSources: ["https://docs.docker.com/language/python/"],
    requiredQuizScore: 80,
    orderIndex: 30,
  },
  {
    id: 31,
    title: "Testing & Deployment",
    phase: "Production",
    difficulty: 4,
    estimatedMinutes: 45,
    xp: 150,
    goal: "Write tests and deploy to production.",
    learningObjectives: [
      "Write unit tests with pytest",
      "Test fixtures and mocking",
      "CI/CD pipeline concepts",
      "Deploy to cloud (Railway/Render)",
    ],
    prerequisites: [30],
    projectFeature: "Write tests for the analyzer and deploy to production.",
    officialSources: ["https://docs.pytest.org/en/stable/"],
    requiredQuizScore: 85,
    orderIndex: 31,
  },
]

export function getMissionById(id: number): MissionDefinition | undefined {
  return MISSIONS.find((m) => m.id === id)
}

export function getMissionsByPhase(phase: string): MissionDefinition[] {
  return MISSIONS.filter((m) => m.phase === phase)
}

export function getPrerequisites(missionId: number): MissionDefinition[] {
  const mission = getMissionById(missionId)
  if (!mission) return []
  return MISSIONS.filter((m) => mission.prerequisites.includes(m.id))
}

export function getTotalMissions(): number {
  return MISSIONS.length
}
