-- ============================================================
-- Pythmaster: Seed Data — 31 Missions across 6 Phases
-- ============================================================

INSERT INTO missions (id, title, phase, difficulty, estimated_minutes, xp, goal, learning_objectives, prerequisites, project_feature, official_sources, required_quiz_score, order_index) VALUES
-- Phase 1: Python Foundations (8 missions)
(1,  'Hello, Python!',       'Python Foundations', 1, 20, 50,  'Write your first Python program and understand what a variable is.',                                             '["Use the print() function","Create and assign variables","Understand basic data types (str, int, float)","Write comments"]',                                                        '{}',       'Display welcome message for the Crypto Exchange Analyzer.',                                          '{"https://docs.python.org/3/tutorial/introduction.html"}',                                                                         75, 1),
(2,  'Data Types & Operators','Python Foundations', 1, 25, 60,  'Work with different data types and perform calculations.',                                                        '["Use int, float, str, bool types","Perform arithmetic operations","Use comparison operators","Type conversion with int(), float(), str()"]',                                            '{1}',      'Calculate basic crypto trading metrics (price difference, percentage change).',                         '{"https://docs.python.org/3/library/stdtypes.html"}',                                                                               75, 2),
(3,  'Input & Output',       'Python Foundations', 1, 25, 60,  'Make interactive programs that respond to user input.',                                                          '["Use input() to get user data","Format strings with f-strings","Handle input type conversion","Basic error prevention"]',         '{1,2}',    'Ask user for crypto symbol and display formatted price info.',                                         '{"https://docs.python.org/3/tutorial/inputoutput.html"}',                                                                          75, 3),
(4,  'Decision Engine',      'Python Foundations', 1, 30, 80,  'Make programs that make decisions using conditions.',                                                            '["Use if, elif, else statements","Combine conditions with and, or, not","Nested conditions","Truthy and falsy values"]',            '{1,2,3}',  'Build a trading signal engine: BUY, SELL, or HOLD based on price thresholds.',                        '{"https://docs.python.org/3/tutorial/controlflow.html#if-statements"}',                                                             80, 4),
(5,  'Loops',                'Python Foundations', 2, 30, 90,  'Automate repetitive tasks with loops.',                                                                          '["Use for loops with range()","Iterate over strings and lists","Use while loops","break and continue statements"]',                 '{4}',      'Process multiple crypto prices in a loop and calculate averages.',                                    '{"https://docs.python.org/3/tutorial/controlflow.html#for-statements"}',                                                            80, 5),
(6,  'Lists',                'Python Foundations', 2, 30, 90,  'Store and manipulate ordered collections of data.',                                                              '["Create and access lists","List methods: append, remove, pop, sort","List slicing [start:stop:step]","Nested lists"]',             '{5}',      'Store historical prices in a list and compute simple moving averages.',                               '{"https://docs.python.org/3/tutorial/datastructures.html#more-on-lists"}',                                                          80, 6),
(7,  'Functions',            'Python Foundations', 2, 35, 100, 'Write reusable, organized code with functions.',                                                                 '["Define functions with def","Parameters and arguments","Return values","Scope (local vs global variables)"]',                       '{6}',      'Move price calculations into reusable functions.',                                                  '{"https://docs.python.org/3/tutorial/controlflow.html#defining-functions"}',                                                         80, 7),
(8,  'Error Handling',       'Python Foundations', 2, 30, 80,  'Write robust code that handles errors gracefully.',                                                              '["Use try/except blocks","Handle specific exceptions","Use else and finally","Raise exceptions intentionally"]',                     '{7}',      'Add input validation and error handling to the crypto analyzer.',                                    '{"https://docs.python.org/3/tutorial/errors.html"}',                                                                               80, 8),

-- Phase 2: Data Structures (6 missions)
(9,  'Tuples & Sets',        'Data Structures', 2, 30, 80,  'Use immutable sequences and unique collections.',                                                                '["Create and use tuples","Tuple unpacking","Create and use sets","Set operations (union, intersection, difference)"]',              '{8}',      'Store trading pairs as tuples and track unique exchanges with sets.',                                '{"https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences"}',                                                   80, 9),
(10, 'Dictionaries',         'Data Structures', 2, 35, 100, 'Master key-value data storage.',                                                                                 '["Create and access dictionaries","Dictionary methods: get, keys, values, items","Nested dictionaries","Dictionary comprehensions (intro)"]', '{9}', 'Build a crypto portfolio tracker using dictionaries.',                                               '{"https://docs.python.org/3/tutorial/datastructures.html#dictionaries"}',                                                          80, 10),
(11, 'Comprehensions',       'Data Structures', 2, 30, 90,  'Write concise, Pythonic data transformations.',                                                                  '["List comprehensions","Dict comprehensions","Set comprehensions","Filtering with if in comprehensions"]',                           '{10}',     'Transform exchange data efficiently with comprehensions.',                                          '{"https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions"}',                                                    80, 11),
(12, 'Iterators & Generators','Data Structures', 3, 35, 110,'Understand lazy evaluation and memory-efficient iteration.',                                                     '["iter() and next()","Create generators with yield","Generator expressions","Memory efficiency concepts"]',                          '{11}',     'Stream large price datasets with generators.',                                                   '{"https://docs.python.org/3/tutorial/classes.html#iterators"}',                                                                    80, 12),
(13, 'String Manipulation',  'Data Structures', 2, 25, 70,  'Master text processing techniques.',                                                                             '["String methods: split, join, strip, replace","Regular expressions with re module","String formatting techniques","Unicode handling basics"]', '{8}', 'Parse and clean exchange names and trading pair strings.',                                        '{"https://docs.python.org/3/library/string.html","https://docs.python.org/3/library/re.html"}',                                    80, 13),
(14, 'Collections Module',   'Data Structures', 3, 30, 90,  'Use specialized container datatypes from the standard library.',                                                 '["namedtuple for lightweight objects","defaultdict for default values","Counter for counting","deque for efficient queues"]',       '{12}',     'Track trade frequency with Counter and order book with deque.',                                    '{"https://docs.python.org/3/library/collections.html"}',                                                                           80, 14),

-- Phase 3: Files & APIs (4 missions)
(15, 'File I/O',             'Files & APIs', 2, 30, 80,     'Read from and write to files on disk.',                                                                          '["Open files with open()","Read modes: r, w, a","Use with statements (context managers)","Read lines and parse text files"]',       '{8}',      'Save and load exchange data from text files.',                                                  '{"https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files"}',                                                80, 15),
(16, 'CSV Processing',       'Files & APIs', 2, 30, 90,     'Work with tabular data using the csv module.',                                                                   '["Read CSV with csv.reader()","Write CSV with csv.writer()","DictReader and DictWriter","Handle headers and encoding"]',            '{15}',     'Import exchange rate history from CSV files.',                                                   '{"https://docs.python.org/3/library/csv.html"}',                                                                                   80, 16),
(17, 'JSON & APIs',          'Files & APIs', 3, 35, 110,    'Work with JSON data and make HTTP requests.',                                                                    '["Parse JSON with json.loads()","Serialize with json.dumps()","Make HTTP requests with requests library","Handle API responses and status codes"]', '{16}', 'Fetch live crypto prices from a public REST API.',                                             '{"https://docs.python.org/3/library/json.html"}',                                                                                 80, 17),
(18, 'API Auth & Rate Limits','Files & APIs', 3, 35, 100,   'Work with authenticated APIs and handle rate limits.',                                                           '["API key authentication","Rate limit handling with time.sleep()","Error handling for API failures","Environment variables with os.getenv()"]', '{17}', 'Connect to CoinGecko or Binance API with proper error handling.',                                 '{"https://docs.python.org/3/library/os.html#os.getenv"}',                                                                           80, 18),

-- Phase 4: Data Engineering (5 missions)
(19, 'NumPy Essentials',     'Data Engineering', 3, 40, 120,'Perform fast numerical computations with NumPy.',                                                                '["Create numpy arrays","Array operations and broadcasting","Statistical functions (mean, std, median)","Boolean indexing"]',         '{12}',     'Compute advanced price statistics with NumPy arrays.',                                            '{"https://numpy.org/doc/stable/user/quickstart.html"}',                                                                            80, 19),
(20, 'Pandas Fundamentals',  'Data Engineering', 3, 45, 130,'Master DataFrames for tabular data analysis.',                                                                   '["Create DataFrames from dicts, lists, CSV","Select columns and rows (loc, iloc)","Filter and sort data","Basic aggregations (groupby)"]', '{19}', 'Build a full crypto data analysis pipeline with Pandas.',                                         '{"https://pandas.pydata.org/docs/getting_started/intro_tutorials/"}',                                                             80, 20),
(21, 'Pandas Advanced',      'Data Engineering', 3, 40, 120,'Advanced data manipulation with Pandas.',                                                                         '["Merge and join DataFrames","Pivot tables","Time series handling","Apply and transform"]',                                          '{20}',     'Merge multiple exchange data sources and create pivot reports.',                                  '{"https://pandas.pydata.org/docs/user_guide/merging.html"}',                                                                       80, 21),
(22, 'DuckDB',               'Data Engineering', 3, 40, 120,'Query data with SQL using an embedded analytical database.',                                                     '["Connect to DuckDB","Run SQL queries on DataFrames","Import/export CSV and Parquet","Aggregations and window functions"]',          '{21}',     'Run complex SQL analytics on crypto data with DuckDB.',                                          '{"https://duckdb.org/docs/"}',                                                                                                    80, 22),
(23, 'PyArrow & Parquet',    'Data Engineering', 3, 35, 100,'Work with columnar data formats for high performance.',                                                          '["Read/write Parquet files","Arrow tables vs Pandas","Columnar data concepts","Performance comparison"]',                            '{22}',     'Store and query historical data in Parquet format.',                                            '{"https://arrow.apache.org/docs/python/"}',                                                                                       80, 23),

-- Phase 5: ETL Pipelines (4 missions)
(24, 'Data Cleaning',        'ETL Pipelines', 3, 35, 110,   'Clean and prepare messy real-world data.',                                                                       '["Handle missing values","Remove duplicates","Fix data types","Outlier detection"]',                                                '{20}',     'Clean raw exchange data from multiple sources.',                                                '{"https://pandas.pydata.org/docs/user_guide/missing_data.html"}',                                                                 80, 24),
(25, 'Data Validation',      'ETL Pipelines', 3, 30, 90,    'Validate data quality programmatically.',                                                                        '["Schema validation concepts","Write validation rules","Data quality metrics","Generate validation reports"]',                       '{24}',     'Validate incoming exchange data before processing.',                                           '{"https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.validate.html"}',                                                 80, 25),
(26, 'Transformations',      'ETL Pipelines', 4, 40, 120,   'Build reusable data transformation pipelines.',                                                                  '["Chain transformations","Feature engineering basics","Normalization and scaling","Date/time transformations"]',                     '{25}',     'Build feature engineering pipeline for trading signals.',                                       '{"https://pandas.pydata.org/docs/user_guide/10min.html"}',                                                                        80, 26),
(27, 'ETL Pipeline Design',  'ETL Pipelines', 4, 45, 140,   'Design and implement complete ETL workflows.',                                                                   '["Extract from multiple sources","Transform with validation","Load to database/files","Pipeline orchestration basics"]',             '{26}',     'Build complete ETL pipeline: fetch → clean → store crypto data.',                                 '{"https://docs.python.org/3/howto/logging.html"}',                                                                                80, 27),

-- Phase 6: Production (4 missions)
(28, 'FastAPI Basics',       'Production', 3, 40, 120,      'Build REST APIs with FastAPI.',                                                                                  '["Create FastAPI app","Define routes and path parameters","Request/response models with Pydantic","Auto-generated docs"]',          '{18}',     'Create a REST API serving crypto analysis results.',                                            '{"https://fastapi.tiangolo.com/tutorial/first-steps/"}',                                                                          80, 28),
(29, 'FastAPI Advanced',     'Production', 4, 45, 130,      'Production-grade APIs with middleware and background tasks.',                                                    '["Dependency injection","Middleware","Background tasks","Error handling middleware"]',                                              '{28}',     'Add caching and rate limiting to the crypto API.',                                              '{"https://fastapi.tiangolo.com/tutorial/middleware/"}',                                                                            80, 29),
(30, 'Docker',               'Production', 3, 35, 100,      'Containerize Python applications.',                                                                              '["Write Dockerfiles","Build and run containers","Docker Compose for multi-service","Volume mounting for dev"]',                      '{29}',     'Dockerize the crypto analyzer API with Docker Compose.',                                         '{"https://docs.docker.com/language/python/"}',                                                                                    80, 30),
(31, 'Testing & Deployment', 'Production', 4, 45, 150,      'Write tests and deploy to production.',                                                                           '["Write unit tests with pytest","Test fixtures and mocking","CI/CD pipeline concepts","Deploy to cloud (Railway/Render)"]',          '{30}',     'Write tests for the analyzer and deploy to production.',                                         '{"https://docs.pytest.org/en/stable/"}',                                                                                          85, 31)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  phase = EXCLUDED.phase,
  difficulty = EXCLUDED.difficulty,
  estimated_minutes = EXCLUDED.estimated_minutes,
  xp = EXCLUDED.xp,
  goal = EXCLUDED.goal,
  learning_objectives = EXCLUDED.learning_objectives,
  prerequisites = EXCLUDED.prerequisites,
  project_feature = EXCLUDED.project_feature,
  official_sources = EXCLUDED.official_sources,
  required_quiz_score = EXCLUDED.required_quiz_score,
  order_index = EXCLUDED.order_index;

-- Reset sequence
SELECT setval('missions_id_seq', (SELECT MAX(id) FROM missions));
